"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-16q72^xgubn1xnhzx#+z28va8)sb^f2_4628zt#=rc1brsabzm"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "celerantcms.cumulusbetasites.com"]


# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ecommerce",
    "cart",
    "mptt",
    "authentications",
    "checkout",
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "core.urls"


#  load templates from root of project
TEMP_DIR = os.path.join(BASE_DIR, "templates")
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMP_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "ecommerce.context_processors.categories",
                "ecommerce.context_processors.cartGlobal",
                "ecommerce.context_processors.logo_img",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "ecommerce",
        "USER": "postgres",
        "PASSWORD": "123456",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


STATIC_URL = "/static/"

MEDIA_URL = "/media/"

if DEBUG:

    STATICFILES_DIRS = [os.path.join(BASE_DIR, "public")]

else:

    STATIC_ROOT = os.path.join(BASE_DIR, "public")


MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "authentications.CustomUser"  # Replace 'yourappname' with the actual name of your app


# Use Gmail's SMTP server for sending emails
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "your-gmail-email@gmail.com"  # Replace with your Gmail email address
EMAIL_HOST_PASSWORD = "your-app-password"  # Replace with the generated App Password

"""Generate an App Password:

Go to your Google Account settings (https://myaccount.google.com/).
In the left sidebar, click on "Security."
Scroll down to the "Signing in to Google" section and click on "App passwords."
Generate a new App Password for your Django application.
Choose "Other (Custom Name)" to specify a name for your app password.
Google will generate a unique password for your application. Copy it; you'll need it for the EMAIL_HOST_PASSWORD setting.
Update Your Django Settings:

Replace 'your-gmail-email@gmail.com' with your actual Gmail email address and 'your-app-password' with the generated App Password."""

BASE_URL="http://localhost:8000"

# Paypal Sandbox creds
PAYPAL_CLIENT_ID = 'AWbojvkP1QJy2XflMyTHDnzgKGsmzom2sxPmVUD9SAgdIm-oXo8jOSljyEREA3o4mxupFDeOeJ-w_cs-'
PAYPAL_SECRET = 'ECVMX7fwEGB7vP_fidGmEVC7gGGvJdCyEIW17oib2dteKrVuj9aILRgWPFw4UWNNu-qH4ctNQ5iHQUDE'
PAYPAL_MODE = 'sandbox'  # Change to 'live' for production

#AUTHORIZE.NET
AUTHORIZENET_API_LOGIN_ID = '8tFD2kqZ652VFRvS5whurJ2bggUZsEbvaD4v69EWW9Bp7PfRWG54jj38f6gHaku3'
AUTHORIZENET_TRANSACTION_KEY = '36B5h55G54vkeZgQ'


if DEBUG:

    MIDDLEWARE += (
        'debug_toolbar.middleware.DebugToolbarMiddleware',
    )
    INSTALLED_APPS += (
        'debug_toolbar',
    )
    INTERNAL_IPS = ('127.0.0.1',)
    DEBUG_TOOLBAR_CONFIG = {
        'INTERCEPT_REDIRECTS': False,
    }
    
    
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "my_cache_table",
    }
}  