# Generated by Django 4.2.5 on 2023-10-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='billing_address_line2',
        ),
        migrations.AddField(
            model_name='customuser',
            name='billing_address_line3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
