# Generated by Django 4.2.5 on 2023-10-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0006_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='billing_first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='billing_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shipping_first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shipping_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
